// 基本資訊

const SITE_NAME = import.meta.env.VITE_SITE_NAME
const DESCRIPTION = import.meta.env.VITE_SITE_DESCRIPTION
const DEMO_EMAIL = import.meta.env.VITE_DEMO_AUTH_EMAIL
const DEMO_PASSWORD = import.meta.env.VITE_DEMO_AUTH_PASSWORD
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY

// 表格相關

const PAGE_SIZE_OPTIONS = ["10", "20", "50", "100"]
const DEFAULT_PAGE_SIZE = 10

export { SITE_NAME, DESCRIPTION, DEMO_EMAIL, DEMO_PASSWORD, SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, PAGE_SIZE_OPTIONS, DEFAULT_PAGE_SIZE }
