/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedLayoutRouteImport } from './routes/_authenticated/_layout'
import { Route as AuthenticatedLayoutSettingIndexRouteImport } from './routes/_authenticated/_layout/setting/index'
import { Route as AuthenticatedLayoutProductListIndexRouteImport } from './routes/_authenticated/_layout/product-list/index'
import { Route as AuthenticatedLayoutDashboardIndexRouteImport } from './routes/_authenticated/_layout/dashboard/index'
import { Route as AuthenticatedLayoutOrderManagementOrderListIndexRouteImport } from './routes/_authenticated/_layout/order-management/order-list/index'
import { Route as AuthenticatedLayoutOrderManagementFeedbackIndexRouteImport } from './routes/_authenticated/_layout/order-management/feedback/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLayoutSettingIndexRoute =
  AuthenticatedLayoutSettingIndexRouteImport.update({
    id: '/setting/',
    path: '/setting/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutProductListIndexRoute =
  AuthenticatedLayoutProductListIndexRouteImport.update({
    id: '/product-list/',
    path: '/product-list/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutDashboardIndexRoute =
  AuthenticatedLayoutDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutOrderManagementOrderListIndexRoute =
  AuthenticatedLayoutOrderManagementOrderListIndexRouteImport.update({
    id: '/order-management/order-list/',
    path: '/order-management/order-list/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutOrderManagementFeedbackIndexRoute =
  AuthenticatedLayoutOrderManagementFeedbackIndexRouteImport.update({
    id: '/order-management/feedback/',
    path: '/order-management/feedback/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedLayoutDashboardIndexRoute
  '/product-list': typeof AuthenticatedLayoutProductListIndexRoute
  '/setting': typeof AuthenticatedLayoutSettingIndexRoute
  '/order-management/feedback': typeof AuthenticatedLayoutOrderManagementFeedbackIndexRoute
  '/order-management/order-list': typeof AuthenticatedLayoutOrderManagementOrderListIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedLayoutDashboardIndexRoute
  '/product-list': typeof AuthenticatedLayoutProductListIndexRoute
  '/setting': typeof AuthenticatedLayoutSettingIndexRoute
  '/order-management/feedback': typeof AuthenticatedLayoutOrderManagementFeedbackIndexRoute
  '/order-management/order-list': typeof AuthenticatedLayoutOrderManagementOrderListIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_layout': typeof AuthenticatedLayoutRouteWithChildren
  '/_authenticated/_layout/dashboard/': typeof AuthenticatedLayoutDashboardIndexRoute
  '/_authenticated/_layout/product-list/': typeof AuthenticatedLayoutProductListIndexRoute
  '/_authenticated/_layout/setting/': typeof AuthenticatedLayoutSettingIndexRoute
  '/_authenticated/_layout/order-management/feedback/': typeof AuthenticatedLayoutOrderManagementFeedbackIndexRoute
  '/_authenticated/_layout/order-management/order-list/': typeof AuthenticatedLayoutOrderManagementOrderListIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/product-list'
    | '/setting'
    | '/order-management/feedback'
    | '/order-management/order-list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/product-list'
    | '/setting'
    | '/order-management/feedback'
    | '/order-management/order-list'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/_layout'
    | '/_authenticated/_layout/dashboard/'
    | '/_authenticated/_layout/product-list/'
    | '/_authenticated/_layout/setting/'
    | '/_authenticated/_layout/order-management/feedback/'
    | '/_authenticated/_layout/order-management/order-list/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_layout': {
      id: '/_authenticated/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_layout/setting/': {
      id: '/_authenticated/_layout/setting/'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof AuthenticatedLayoutSettingIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/product-list/': {
      id: '/_authenticated/_layout/product-list/'
      path: '/product-list'
      fullPath: '/product-list'
      preLoaderRoute: typeof AuthenticatedLayoutProductListIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/dashboard/': {
      id: '/_authenticated/_layout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedLayoutDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/order-management/order-list/': {
      id: '/_authenticated/_layout/order-management/order-list/'
      path: '/order-management/order-list'
      fullPath: '/order-management/order-list'
      preLoaderRoute: typeof AuthenticatedLayoutOrderManagementOrderListIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/order-management/feedback/': {
      id: '/_authenticated/_layout/order-management/feedback/'
      path: '/order-management/feedback'
      fullPath: '/order-management/feedback'
      preLoaderRoute: typeof AuthenticatedLayoutOrderManagementFeedbackIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
  }
}

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedLayoutDashboardIndexRoute: typeof AuthenticatedLayoutDashboardIndexRoute
  AuthenticatedLayoutProductListIndexRoute: typeof AuthenticatedLayoutProductListIndexRoute
  AuthenticatedLayoutSettingIndexRoute: typeof AuthenticatedLayoutSettingIndexRoute
  AuthenticatedLayoutOrderManagementFeedbackIndexRoute: typeof AuthenticatedLayoutOrderManagementFeedbackIndexRoute
  AuthenticatedLayoutOrderManagementOrderListIndexRoute: typeof AuthenticatedLayoutOrderManagementOrderListIndexRoute
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedLayoutDashboardIndexRoute:
    AuthenticatedLayoutDashboardIndexRoute,
  AuthenticatedLayoutProductListIndexRoute:
    AuthenticatedLayoutProductListIndexRoute,
  AuthenticatedLayoutSettingIndexRoute: AuthenticatedLayoutSettingIndexRoute,
  AuthenticatedLayoutOrderManagementFeedbackIndexRoute:
    AuthenticatedLayoutOrderManagementFeedbackIndexRoute,
  AuthenticatedLayoutOrderManagementOrderListIndexRoute:
    AuthenticatedLayoutOrderManagementOrderListIndexRoute,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
